services:
  database_dk: 
    image: postgres
    container_name: database_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker_postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    restart: always
    build: .
    container_name: rentx
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata: